### ISSUE TITLE
youdumbass

### ISSUE THREAD

**Issue by sukmadic** [Wizz1337/TikTokMassBotting#90]
don't commit any changes before you test your code dumbass

**Comment by grishatop1** [comment]
what's your issue?

**Comment by Aljoberg** [comment]
you open an issue to **explain the issue you got**, not to say some bullshit. go fix it on your own instead of just forking the repo and downloading the code **and** then saying "dumbass". Remember, this guy made us have millions of shares so i'd suggest you *actually* opening an issue with a reason.

**Comment by Wizz1337** [comment]
thanks
